config/routes.rb
Rails.application.routes.draw do
  get 'hotels/:id/available_rooms' => 'hotels#available_rooms', as: 'hotel_available_rooms'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :charges, only: [:new, :create]
  resources :users, only: [:index] do
    resources :bookings, shallow: true
  end

  root 'users#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :user
  belongs_to :hotel
  belongs_to :room
  has_one :charge

  scope :current, -> (user_id, month_start, month_end) { where(user_id: user_id).where('check_in_date BETWEEN ? and ? or check_out_date BETWEEN ? and ?', month_start, month_end, month_start, month_end)}

  validates :user_id, presence: true
  validates :hotel_id, presence: true
  validates :room_id, presence: true
  validates :check_in_date, presence: true
  validates :check_out_date, presence: true

  def charges_in_cents
    (total_charges * 100).to_i
  end

  def total_charges
    (number_of_days_stay * room.room_type.nightly_charge).to_f
  end

  def number_of_days_stay
    days = (check_out_date.to_date - check_in_date.to_date).to_i
    (days === 0 ? 1 : days)
  end

  def description
    "Hotel: #{self.hotel.name}, Room: #{self.room.room_label}"
  end
end

app/models/charge.rb
class Charge < ActiveRecord::Base

  belongs_to :booking

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base

  has_many :rooms
  has_many :room_types
  has_many :bookings

  def available_rooms(start_date, end_date)
    self.rooms.where.not(id: booked_rooms(DateTime.parse(start_date), DateTime.parse(end_date)))
  end

  def booked_rooms(start_date, end_date)
    self.bookings.where('(EXTRACT(EPOCH FROM (? - check_out_date)) * EXTRACT(EPOCH FROM (check_in_date - ?)) >= 0)', start_date, end_date).map(&:room_id)
  end
end

app/models/room.rb
class Room < ActiveRecord::Base

  belongs_to :hotel, counter_cache: true
  belongs_to :room_type
  has_many :bookings

  validates :hotel_id, presence: true
  validates :room_type_id, presence: true
  validates :room_number, presence: true

  def room_label
    "#{self.room_number} - #{self.room_type.name}"
  end
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base

  belongs_to :hotel
  has_many :rooms

  validates :hotel_id, presence: true
  validates :name, presence: true
  validates :nightly_charge, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token

  has_many :bookings
  has_many :hotels, through: :bookings
  has_many :rooms, through: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :authentication_token])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  serialization_scope :view_context
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  def index
    respond_to do |format|
      format.html {redirect_to :root}
      format.json { render json: Booking.current(params[:user_id], params[:start], params[:end]) }
    end
  end

  # GET /bookings/1
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new(user_id: params[:user_id])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bookings/1
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
    redirect_to root_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.require(:booking)
            .permit(:user_id, :hotel_id, :room_id, :check_in_date, :check_out_date, :stay_description)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_booking, only: [:new]

  def new
  end

  def create
    @booking = Booking.find_by_id(session[:booking_id])
    charge_status = ChargesService.new(@booking, params).charge
    redirect_to booking_path(@booking), notice: "Payment: #{charge_status}" and return
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path(booking_id: @booking.id)
  end

  private

  def set_booking
    if params["booking_id"].blank?
      redirect_to root_path, notice: 'Must pay charges from a Booking' and return
    end

    session[:booking_id] = params["booking_id"]
    @booking = Booking.find_by_id(params["booking_id"])
    @amount = @booking.charges_in_cents
    @amount_dollars = @booking.total_charges
    @description = @booking.description

  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  def available_rooms
    respond_to do |format|
      format.json { render json: Hotel.find(params[:id]).available_rooms(params[:start_date], params[:end_date]) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/hotel_helper.rb
module HotelHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.slim
= simple_form_for(@booking, url: path) do |f|
  - if @booking.errors.any?
    #error_explanation
      h2 = "#{pluralize(@booking.errors.count, "error")} prohibited this booking from being saved:"
      ul
        - @booking.errors.full_messages.each do |message|
          li = message

  .form-inputs
    = f.input :user_id, as: :hidden
    = f.input :check_in_date
    = f.input :check_out_date
    = f.input :hotel_id, collection: Hotel.all
    = f.input :room_id, collection: Room.all.map{ |r| [r.room_label, r.id] }
    = f.input :stay_description, as: :string, minlength: 0
  .actions = f.submit

app/views/bookings/edit.html.slim
.booking_form
  h1 Editing booking

  == render 'form', path: booking_path(@booking)

  br
  = link_to 'Show', @booking, class: 'button'

app/views/bookings/new.html.slim
.booking_form
  h1 New booking

  == render 'form', path: user_bookings_path(user_id: @booking.user_id)

app/views/bookings/show.html.slim
.booking_form
  h1 Booking

  .details
    p.fields
      span.field Check In Date:
      span.value = @booking.check_in_date
    p.fields
      span.field Check Out Date:
      span.value = @booking.check_out_date
    p.fields
      span.field Hotel:
      span.value = @booking.hotel.name
    p.fields
      span.field Room:
      span.value = @booking.room.room_label
    p.fields
      span.field Stay Description:
      span.value = @booking.stay_description
    p.fields
      span.field Total Charges:
      span.value = "$#{@booking.total_charges} #{@booking.charge.present? ? 'PAID' : 'DUE'}"


    = link_to 'Edit', edit_booking_path(@booking), class: 'button'
    - if @booking.charge.blank?
      = link_to 'Pay Charges', new_charge_path(booking_id: @booking.id), class: 'button success'
    = link_to 'Destroy', @booking, data: { confirm: 'Are you sure?' }, method: :delete, class: 'button danger'

app/views/charges/new.html.erb
<div class="booking_form">
  <h2>Charges for Booking</h2>
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <p class="charge_amount">Amount: $<%= @amount_dollars %></p>
        <p class="charge_description">Description: <%= @description %></p>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @description %>"
            data-amount="<%= @amount %>"
            data-locale="auto"></script>
  <% end %>
</div>

app/views/layouts/_menu.html.slim
ul
  li = link_to 'Home', root_path
  li = link_to 'Book a Room', new_user_booking_path(user_id: current_user.id)
  li.right = link_to 'Logout', destroy_user_session_path, method: :delete
  li.right = link_to 'Admin', admin_root_path, target: '_admin'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Code Challenge
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
body

.header
  span.title TAKL Property Management

.contents
  - if user_signed_in?
    == render 'layouts/menu'

  - if notice.present?
    p.notifications.notice == notice
  - if alert.present?
    p.notifications.alert == alert

  - if user_signed_in?
    == yield
  - else
    .user_tasks
      == yield

app/views/users/index.html.slim
h1.center Bookings Dashboard

#calendar-container
  #bookings-calendar data-userid="#{current_user.id}" data-token="#{current_user.authentication_token}"